name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - uses: actions/checkout@v1
    - run: make test
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.txt
