name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19', '1.20', '1.21']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: make test
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.txt
